version: '3'
services:
  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    build: ./
    image: 'application-web/vuejs-node:latest'
    container_name: web
    ports:
      - '3000:3000'
